[tox]
envlist = py{311}
requires = tox-conda

[testenv]
setenv =
    PYTHONUNBUFFERED = 1
deps=
    pip
    wheel
    setuptools<71
    pytest
    Cython
    numpy==2.1.1
    pytest-forked
    pytest-xdist
whitelist_externals = pytest
    /bin/rm
commands =
    pytest -s --log-cli-level=DEBUG --forked -n 1 -v -x watson/tests/

[gh]
python =
    3.11 = py311, type
allowlist_externals = rm
